### ISSUE TITLE
Drop k param from List'

### ISSUE THREAD

**Issue by jvliwanag** [PureFunctor/purescript-typelevel-lists#2]
Hi!

Wondering if it would be better to remove `k` from `List' k`. You'd end up with:

```
data List'

foreign import data Nil' :: List'
foreign import data Cons' :: forall k. k -> List' -> List'

infixr 1 type Cons' as :>

type X = "foo" :> Int :> Nil'
```

The nice thing is you won't need `Item'` anymore and I believe there's no loss of information.

**Comment by purefunctor** [comment]
Hello, I originally intended the library to only have heterogeneous lists, considering `0.13.8`, but now that `0.14.0` introduced PolyKinds, I figured it's only appropriate to allow homogeneous lists as well for `1.0.0` :slightly_smiling_face:

**Comment by purefunctor** [comment]
On second thought, there doesn't seem to be much use for homogeneity in this context; I'll probably just provide a separate interface living under `Data.List.Hom` if need be.

**Comment by jvliwanag** [comment]
I'm afraid I don't understand that well. I'd appreciate your help on this.

What do we mean by homogeneous vs heterogeneous?

From what I understand, `List` without the `k` is heterogeneous since it can cover `Cons`-ing of different kinds?

Since the heterogeneous use cases cover the homogeneous ones entirely, then figured it can be removed.

To be honest, my motivation for the pull request is that I just preferred not to have to wrap everything onto `Item` 😄

**Comment by purefunctor** [comment]
Ah, I meant homogeneous as in having the same kind for all `List'` items, essentially disallowing something like:
```purescript
foo :: Proxy ("Type" :> String :> Nil)
foo = Proxy

-- Could not match kind
--
--   Symbol
--
-- with kind
--
--   Type
```
> Since the heterogeneous use cases cover the homogeneous ones entirely, then figured it can be removed.

That's true and I'm not opposed to restoring `k` in the future e.g. the next major release as well. Anyhow, I think we can move discussions about this on a separate issue.
