### ISSUE TITLE
Add value level lists

### ISSUE THREAD

**Issue by jvliwanag** [PureFunctor/purescript-typelevel-lists#5]
If the kind for each Cons'd is `Type`, can we have a matching data declaration?

I should be able to do:

```
foo :: Int :> String :> Boolean :> Nil'
foo = 5 :> "baz" :> true :> Nil'
```

We can create purescript-heterogeneous instances for this data type to allow for generic mapping and folding.

One argument against adding this though is that this sort of exists already by way of Tuple:

```
import Data.Tuple.Nested ((/\), type (/\))

foo :: Int /\ String /\ Boolean /\ Unit
foo = 5 /\ "baz" /\ true /\ unit
```

**Comment by purefunctor** [comment]
Assuming it'd work like:
```purescript
data Nil' = Nil'

data Cons' :: forall a b. a -> b -> Type
data Cons' m n = Cons'

infixr 1 type Cons' as :>

foo :: Int :> String :> Boolean :> Nil'
foo = 5 :> "baz" :> true :> Nil'
```
would `Nil'` still have to be present to construct the list? It'll feel redundant given Tuple otherwise.

**Comment by jvliwanag** [comment]
I was thinking more along the lines of:

```purescript
data Cons' a b = Cons' a b
data Nil' = Nil'
```

So mapping, folding etc still makes sense.

Then again, this is just be nested `Tuple` with a `Nil` terminator. So perhaps it's redundant. Closing this for now until I have something more concrete.
