### ISSUE TITLE
Issue in Concat type class

### ISSUE THREAD

**Issue by JordanMartinez** [PureFunctor/purescript-typelevel-lists#7]
Correct me if I'm wrong, but I'm pretty sure this [instance is wrong](https://github.com/PureFunctor/purescript-typelevel-lists/blob/develop/src/Type/Data/List.purs#L69) because the `ys` is never touched and that once you hit the `Nil'` case on the `xs`, it just gives you `ys` rather than `zs`.

Doesn't what you've written at the type-level work like this at the value-level?
```purescript
concat :: List a -> List a -> List a -> List a
concat Nil y acc = acc
concat (Cons x xs) ys acc = concat xs ys (Cons x acc)
```

Writing this by hand (value-level), shouldn't it be this?
```purescript
concat :: forall a. List a -> List a -> List a
concat xs ys = concatSolve xs ys Nil

concatSolve :: forall a. List a -> List a -> List a -> List a
concatSolve Nil Nil acc = acc
concatSolve (Cons x xs) ys acc = Cons x (concatSolve xs ys acc)
concatSolve xs (Cons y ys) acc = concatSolve xs Nil (Cons y (concatSolve ys acc Nil))
```

**Comment by purefunctor** [comment]
Not necessarily, it works more like a `foldr` in this case:
```purescript
Concat ( Int :> String :> Nil' ) ( Char :> Nil' ) ( Int :> ... )  -- apply concatRec

Concat ( String :> Nil' ) ( Char :> Nil' ) ( Int :> ( String :> ...) )  -- apply concatRec

Concat ( Nil' ) ( Char :> Nil' ) ( Int :> ( String :> ( Char :> 'Nil ) ) ) -- apply concatBase
```
At the value-level, it should operate similarly to:
```purescript
concat :: List a -> List a -> List a
concat Nil ys = ys
concat (Cons x xs) ys = Cons x (xs ++ ys) 
```

**Comment by JordanMartinez** [comment]
Ah.... Yeah, I see how it works now. Thanks for clarifying.
